export const TOGGLE_MAL = 'TOGGLE_MAL';
export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';
export const TOGGLE_SUPP_LIST = 'TOGGLE_SUPP_LIST';
export const REQUEST_SUPP = 'REQUEST_SUPP';
export const GET_SUPP_SUCCESS = 'GET_SUPP_SUCCESS';
export const GET_SUPP_FAILURE = 'GET_SUPP_FAILURE';
export const DISPLAY_MAL = 'DISPLAY_MAL';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';